### PR TITLE
docs: add related to uhtml

### PR DESCRIPTION
**Pull request by Scrum**
It’s not immediately clear what this package is for, if you don’t know about `uhtml` )))

### CODE REVIEW

**Comment by WebReflection** [comment]
Thanks for the hint, but this is about any template literal tag function, not coupled with any specific library, only the examples are.

This works with _lit-html_, _lighterhtml_, _hyperHTML_, _uhtml_, anything else that uses tag functions ... not sure it's worth to list all of them in the README ;-)

**Comment by Scrum** [comment]
> Thanks for the hint, but this is about any template literal tag function, not coupled with any specific library, only the examples are.
> 
> This works with _lit-html_, _lighterhtml_, _hyperHTML_, _uhtml_, anything else that uses tag functions ... not sure it's worth to list all of them in the README ;-)

This can also be added to show the spectrum of use of this package.

**Comment by WebReflection** [comment]
The spectrum is: any template literal tag function, including SSR, SQL (I wouldn't do that ... but ...) etcetera. It's specified that it's a generic string to template literal tag arguments, how can I specify more it's generic?

**Comment by Scrum** [comment]
The list of packages in which this package can be used shows the potential of the degree of universality.

**Comment by WebReflection** [comment]
I've tried to improve the README just recently, I hope that's good enough.

**Pull request closed without merging**
